### ISSUE TITLE
PingEndpointTest test gives 401 error

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guide-kubernetes-microprofile-config#47]
Running it.io.openliberty.guides.ping.PingEndpointTest
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.924 s <<< FAILURE! - in it.io.openliberty.guides.ping.PingEndpointTest
[ERROR] testPingValidService(it.io.openliberty.guides.ping.PingEndpointTest)  Time elapsed: 2.385 s  <<< FAILURE!
java.lang.AssertionError: Incorrect response code from http://10.20.5.134:32000/api/ping/ expected:<200> but was:<401>
	at it.io.openliberty.guides.ping.PingEndpointTest.assertResponse(PingEndpointTest.java:114)
	at it.io.openliberty.guides.ping.PingEndpointTest.testPingValidService(PingEndpointTest.java:66)
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   PingEndpointTest.testPingValidService:66->assertResponse:114 Incorrect response code from http://10.20.5.134:32000/api/ping/ expected:<200> but was:<401>
[INFO] 
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- liberty-maven-plugin:2.6.4:test-stop-server (test-stop-server) @ ping ---
[INFO] CWWKM2102I: Using artifact based assembly archive : io.openliberty:openliberty-runtime:null:RELEASE:zip.
[INFO] CWWKM2102I: Using installDirectory : /home/travis/build/OpenLiberty/guide-kubernetes-microprofile-config/finish/ping/target/liberty/wlp.
[INFO] CWWKM2102I: Using serverName : defaultServer.
[INFO] CWWKM2102I: Using serverDirectory : /home/travis/build/OpenLiberty/guide-kubernetes-microprofile-config/finish/ping/target/liberty/wlp/usr/servers/defaultServer.
[INFO] CWWKM2152I: Stopping server defaultServer.
[INFO] CWWKM2001I: server.config.dir is /home/travis/build/OpenLiberty/guide-kubernetes-microprofile-config/finish/ping/target/liberty/wlp/usr/servers/defaultServer.
[INFO] CWWKM2001I: server.output.dir is /home/travis/build/OpenLiberty/guide-kubernetes-microprofile-config/finish/ping/target/liberty/wlp/usr/servers/defaultServer.
[INFO] CWWKM2001I: Invoke command is [/home/travis/build/OpenLiberty/guide-kubernetes-microprofile-config/finish/ping/target/liberty/wlp/bin/server, stop, defaultServer].
[INFO] 
[INFO] Stopping server defaultServer.
[INFO] Server defaultServer stopped.
[INFO] 
[INFO] --- maven-failsafe-plugin:3.0.0-M1:verify (verify-results) @ ping ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] kube-demo .......................................... SUCCESS [  0.004 s]
[INFO] name ............................................... SUCCESS [ 28.091 s]
[INFO] ping ............................................... FAILURE [ 20.172 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 50.154 s
[INFO] Finished at: 2019-03-27T10:10:12Z
[INFO] Final Memory: 32M/114M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:3.0.0-M1:verify (verify-results) on project ping: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/travis/build/OpenLiberty/guide-kubernetes-microprofile-config/finish/ping/target/test-reports/it for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :ping

**Comment by evelinec** [comment]
Here are the error in the console.log: 

[ERROR   ] CWMCG5003E: The [BackedAnnotatedField] @Inject @ConfigProperty private io.openliberty.guides.name.NameResource.hostname InjectionPoint dependency was not resolved. Error: java.util.NoSuchElementException: CWMCG0015E: The property HOSTNAME was not found in the configuration.
	at com.ibm.ws.microprofile.config.impl.AbstractConfig.getValue(AbstractConfig.java:175)
	at [internal classes]

[ERROR   ] CWMCG5003E: The [BackedAnnotatedField] @Inject @ConfigProperty private io.openliberty.guides.name.NameResource.greeting InjectionPoint dependency was not resolved. Error: java.util.NoSuchElementException: CWMCG0015E: The property GREETING was not found in the configuration.
	at com.ibm.ws.microprofile.config.impl.AbstractConfig.getValue(AbstractConfig.java:175)
	at [internal classes]

[ERROR   ] CWMCG5003E: The [BackedAnnotatedField] @Inject @ConfigProperty private io.openliberty.guides.name.NameResource.hostname InjectionPoint dependency was not resolved. Error: java.util.NoSuchElementException: CWMCG0015E: The property HOSTNAME was not found in the configuration.
	at com.ibm.ws.microprofile.config.impl.AbstractConfig.getValue(AbstractConfig.java:175)
	at [internal classes]

[ERROR   ] CWMCG5003E: The [BackedAnnotatedField] @Inject @ConfigProperty private io.openliberty.guides.name.NameResource.greeting InjectionPoint dependency was not resolved. Error: java.util.NoSuchElementException: CWMCG0015E: The property GREETING was not found in the configuration.
	at com.ibm.ws.microprofile.config.impl.AbstractConfig.getValue(AbstractConfig.java:175)
	at [internal classes]

[ERROR   ] CWWKZ0002E: An exception occurred while starting the application name. The exception message was: com.ibm.ws.container.service.state.StateChangeException: org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type String with qualifiers @ConfigProperty
  at injection point [BackedAnnotatedField] @Inject @ConfigProperty private io.openliberty.guides.name.NameResource.hostname
  at io.openliberty.guides.name.NameResource.hostname(NameResource.java:0)
